version: '3'
services:
  db:
    container_name: contacts_db
    image: postgres:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    ports:
      - '${POSTGRES_PORT}:5432'
